php:
  build: .
  dockerfile: Dockerfile
  ports:
   - "8080:80"
  volumes:
   - .:/var/www
  links:
   - redis
  environment:
     REDIS_URL: "tcp://redis:6379"
redis:
  image: redis:3.2.4
  volumes:
    - ./docker/redis/data:/data
  restart: always
